name: Terraform Tests

on:
  pull_request:
    branches:
      - main  # Tester les modifications sur une pull request vers `main`
  push:
    branches:
      - main  # Tester après un push sur la branche `main`

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Version Terraform que vous souhaitez utiliser

    - name: Initialize Terraform
      working-directory: infrastructure/
      run: terraform init

    - name: Check Terraform Formatting
      working-directory: infrastructure/
      run: terraform fmt -check

    - name: Validate Terraform
      working-directory: infrastructure/
      run: terraform validate 
